### ISSUE TITLE
Learning to see videowall content (memowall.webm) download link

### ISSUE THREAD

**Issue by memoakten** [jceipek/exhibition-returning-the-gaze#6]
Learning to see videowall content (**memowall.webm**) is 140MB (20 minutes long), so I was reluctant to check it into github in case I change it again and every version will be permanently inflating commit history.

It can be downloaded from this folder:
https://www.dropbox.com/sh/k69xmsotw38inla/AACcz2PeJH5kiMF0BSUL66kda?dl=0

direct link to file:
https://www.dropbox.com/s/zylyyqvhswr9ij4/memowall.webm?dl=0

this is the command (on linux) to download it into the current folder
`wget https://www.dropbox.com/s/zylyyqvhswr9ij4/memowall.webm?dl=0 -O memowall.webm `

i.e. `cd` to  `<server>/path/to/exhibition-returning-the-gaze\src\media` before running the command 

(if `wget `gives an error, then install with: `sudo apt update && sudo apt install wget` )

P.S. Maybe all large data files can be stored in a shared dropbox or google drive folder. And then a separate script (part of this git repo) downloads them all into the media folder.

**Comment by memo** [comment]
direct link to file:
https://www.dropbox.com/s/zylyyqvhswr9ij4/memowall.webm?dl=0

this is the command (on linux) to download it into the current folder
`wget https://www.dropbox.com/s/zylyyqvhswr9ij4/memowall.webm?dl=0 -O memowall.webm `

**Comment by memoakten** [comment]
file is in repo now
